/**
 * Seed definitions for all configurable system settings.
 * Used by the seed endpoint to initialize SystemConfig documents.
 */
const systemConfigDefinitions = [
  // ── Authentication ──
  {
    key: "auth.jwt_expiry",
    defaultValue: "24h",
    category: "authentication",
    dataType: "string",
    label: "JWT Token Expiry",
    description: "How long access tokens remain valid. Format: number + s/m/h/d (e.g. 24h, 1d)",
    unit: "",
    validation: { pattern: "^\\d+[smhd]$" },
    requiresRestart: true,
  },
  {
    key: "auth.refresh_token_expiry",
    defaultValue: "7d",
    category: "authentication",
    dataType: "string",
    label: "Refresh Token Expiry",
    description: "How long refresh tokens remain valid before requiring re-login",
    unit: "",
    validation: { pattern: "^\\d+[smhd]$" },
    requiresRestart: true,
  },
  {
    key: "auth.otp_validity_minutes",
    defaultValue: 10,
    category: "authentication",
    dataType: "number",
    label: "OTP Validity",
    description: "Minutes an OTP code remains valid after being sent",
    unit: "minutes",
    validation: { min: 1, max: 60 },
    requiresRestart: false,
  },
  {
    key: "auth.account_lock_duration_minutes",
    defaultValue: 30,
    category: "authentication",
    dataType: "number",
    label: "Account Lock Duration",
    description: "Minutes an account stays locked after exceeding max login attempts",
    unit: "minutes",
    validation: { min: 5, max: 1440 },
    requiresRestart: false,
  },
  {
    key: "auth.max_login_attempts",
    defaultValue: 5,
    category: "authentication",
    dataType: "number",
    label: "Max Login Attempts",
    description: "Number of failed login attempts before the account is locked",
    unit: "attempts",
    validation: { min: 3, max: 20 },
    requiresRestart: false,
  },
  {
    key: "auth.rate_limit_auth_max",
    defaultValue: 10,
    category: "authentication",
    dataType: "number",
    label: "Auth Rate Limit (Max Requests)",
    description: "Maximum login attempts allowed within the rate limit window",
    unit: "requests",
    validation: { min: 3, max: 100 },
    requiresRestart: true,
  },
  {
    key: "auth.rate_limit_auth_window_minutes",
    defaultValue: 15,
    category: "authentication",
    dataType: "number",
    label: "Auth Rate Limit (Window)",
    description: "Time window for the auth rate limiter",
    unit: "minutes",
    validation: { min: 1, max: 60 },
    requiresRestart: true,
  },
  {
    key: "auth.rate_limit_forgot_max",
    defaultValue: 3,
    category: "authentication",
    dataType: "number",
    label: "Forgot Password Rate Limit (Max)",
    description: "Maximum forgot-password requests within the window",
    unit: "requests",
    validation: { min: 1, max: 20 },
    requiresRestart: true,
  },
  {
    key: "auth.rate_limit_forgot_window_minutes",
    defaultValue: 60,
    category: "authentication",
    dataType: "number",
    label: "Forgot Password Rate Limit (Window)",
    description: "Time window for the forgot-password rate limiter",
    unit: "minutes",
    validation: { min: 15, max: 1440 },
    requiresRestart: true,
  },

  // ── File Management ──
  {
    key: "files.upload_size_limit_mb",
    defaultValue: 5,
    category: "file_management",
    dataType: "number",
    label: "File Upload Size Limit",
    description: "Maximum file size for user uploads (profile pictures, attachments)",
    unit: "MB",
    validation: { min: 1, max: 50 },
    requiresRestart: true,
  },
  {
    key: "files.allowed_image_types",
    defaultValue: ["image/jpeg", "image/jpg", "image/png"],
    category: "file_management",
    dataType: "string_array",
    label: "Allowed Image Types",
    description: "MIME types allowed for image uploads",
    unit: "",
    validation: {},
    requiresRestart: true,
  },
  {
    key: "files.body_parser_limit_mb",
    defaultValue: 50,
    category: "file_management",
    dataType: "number",
    label: "Request Body Size Limit",
    description: "Maximum size for JSON request bodies",
    unit: "MB",
    validation: { min: 10, max: 200 },
    requiresRestart: true,
  },

  // ── Communication ──
  {
    key: "comm.priority_check_cron",
    defaultValue: "*/10 * * * * *",
    category: "communication",
    dataType: "string",
    label: "Priority Message Check Interval",
    description: "Cron expression for checking priority messages (6-field format with seconds)",
    unit: "cron",
    validation: {},
    requiresRestart: true,
  },
  {
    key: "comm.escalation_cron",
    defaultValue: "*/2 * * * *",
    category: "communication",
    dataType: "string",
    label: "Escalation Check Interval",
    description: "Cron expression for running message escalation checks",
    unit: "cron",
    validation: {},
    requiresRestart: true,
  },
  {
    key: "comm.agora_token_expiry_seconds",
    defaultValue: 3600,
    category: "communication",
    dataType: "number",
    label: "Agora Token Expiry",
    description: "How long Agora video call tokens remain valid",
    unit: "seconds",
    validation: { min: 300, max: 86400 },
    requiresRestart: false,
  },
  {
    key: "comm.magic_link_expiry_hours",
    defaultValue: 48,
    category: "communication",
    dataType: "number",
    label: "Magic Link Expiry",
    description: "How long family portal magic links remain valid",
    unit: "hours",
    validation: { min: 1, max: 168 },
    requiresRestart: false,
  },

  // ── Caching ──
  {
    key: "cache.pcc_token_ttl_seconds",
    defaultValue: 3300,
    category: "caching",
    dataType: "number",
    label: "PCC Token Cache TTL",
    description: "How long PointClickCare OAuth tokens are cached in Redis",
    unit: "seconds",
    validation: { min: 60, max: 3600 },
    requiresRestart: false,
  },
  {
    key: "cache.pcc_summary_ttl_seconds",
    defaultValue: 300,
    category: "caching",
    dataType: "number",
    label: "PCC Patient Summary Cache TTL",
    description: "How long patient summaries from PCC are cached",
    unit: "seconds",
    validation: { min: 30, max: 3600 },
    requiresRestart: false,
  },
  {
    key: "cache.ai_summary_ttl_minutes",
    defaultValue: 15,
    category: "caching",
    dataType: "number",
    label: "AI Summary Cache TTL",
    description: "How long Claude AI post-session summaries are cached",
    unit: "minutes",
    validation: { min: 1, max: 120 },
    requiresRestart: false,
  },

  // ── System ──
  {
    key: "system.socket_max_buffer_mb",
    defaultValue: 10,
    category: "system",
    dataType: "number",
    label: "Socket.IO Max Buffer Size",
    description: "Maximum buffer size for WebSocket messages",
    unit: "MB",
    validation: { min: 1, max: 100 },
    requiresRestart: true,
  },
  {
    key: "system.pagination_default",
    defaultValue: 10,
    category: "system",
    dataType: "number",
    label: "Default Pagination Size",
    description: "Default number of items per page in list views",
    unit: "items",
    validation: { min: 5, max: 100 },
    requiresRestart: false,
  },
  {
    key: "system.session_timeout_minutes",
    defaultValue: 30,
    category: "system",
    dataType: "number",
    label: "Frontend Session Timeout",
    description: "Minutes of inactivity before the frontend session expires",
    unit: "minutes",
    validation: { min: 5, max: 480 },
    requiresRestart: false,
  },
];

export default systemConfigDefinitions;
